name: Run Python Tests

# Déclenche uniquement lors des PR vers main
on:
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Python (version STABLE)
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      # 3️⃣ Installer uv
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      # 5️⃣ Lancer pytest
      - name: pytest
        run: uv run pytest